micronaut:
  application:
    name: keyManager


# http cliente
endereco.client.itau: ${ITAU_URL:`http://localhost:9091`}
endereco.client.bcb: ${BCB_URL:`http://localhost:8082`}


# mensagem erro
erro.valor.chave.ja.existe: "Essa chave já foi cadatrada"
erro.cliente.nao.existe:  "O cliente nao foi encontrado no sistema do ITAU"
erro.valorchavejaexiste: "Essa chave já foi cadatrada"


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/keymanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
    schema-generate: CREATE_DROP
    dialect: POSTGRES


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
          database-platform: org.hibernate.dialect.PostgreSQL9Dialect

#logging.pattern.console: %msg%n
